### PR TITLE
Rename and add more info in TFJobCondition

### PR DESCRIPTION
**Pull request by ScorpioCPH**
Hi, this PR will:

- Rename `Specs` to `TFReplicaSpecs` in `TFJob.Spec`.
- Add more info in `TFJobCondition`
  - We should use `Condition` first instead of `Phase` (Phase is used for state machine, it is hard to maintain).

@DjangoPeng @gaocegege-caicloud @Jimexist @ddysher PTAL.

### CODE REVIEW

**Comment by gaocegege** [comment]
I think we should change the code in controller to fit the new name.

**Comment by DjangoPeng** [comment]
Yep, we have to do that. So, a corresponding PR is necessary for kubeflow-controller.

**Comment by ScorpioCPH** [comment]
@gaocegege @DjangoPeng Sure, after merging this PR, will update kubeflow-controller.

**Comment by DjangoPeng** [comment]
Good job. Please go ahead. @ScorpioCPH

**Pull request merged**
