### PR TITLE
.gitattrbutes: Linguist friendly

### PR DESCRIPTION
**Pull request by gaocegege-caicloud**
GitHub uses linguist to generate the analytics of the code, the generated code and vendor are computed into the LOC, this PR is to fix the problem.

```bash
After the PR:
$ git-linguist breakdown
{"Makefile":["Makefile"],"Go":["apis/kubeflow/v1alpha1/doc.go","apis/kubeflow/v1alpha1/register.go","apis/kubeflow/v1alpha1/types.go"],"Shell":["hack/update-codegen.sh","hack/verify-codegen.sh"]}
```

### CODE REVIEW

**Comment by gaocegege-caicloud** [comment]
CI is failed because #7 is not merged but Travis CI begins to work, it will be fixed after #7 merged.

**Comment by Jimexist** [comment]
this is really low priority, i wouldn't personally mind about this yet

**Comment by gaocegege-caicloud** [comment]
I am a little 强迫症

**Comment by gaocegege-caicloud** [comment]
PTAL @DjangoPeng

**Comment by DjangoPeng** [comment]
It's make sense for me.

**Pull request merged**
