### PR TITLE
refactor(example): update training examples

### PR DESCRIPTION
**Pull request by DjangoPeng**
We have built `cargo.caicloud.io/clever-base/tensorflow:v1.4.0-example` image locally. The corresponding Dockerfile can be found here https://github.com/caicloud/dockerfile/pull/16 .

If we use the example image, we can get rid of the external dependency.

cc/ @gaocegege-caicloud @zjx-caicloud @ScorpioCPH

### CODE REVIEW

**Comment by DjangoPeng** [comment]
See also: https://github.com/caicloud/kubeflow-clientset/pull/19

**Comment by gaocegege-caicloud** [comment]
Does this image contain the mnist data?

**Comment by DjangoPeng** [comment]
Nope.

> Does this image contain the mnist data?

It only includes the python script.

**Comment by gaocegege-caicloud** [comment]
Then it will not work on dev env since it is in GFW.

**Comment by DjangoPeng** [comment]
I'm not sure that mnist dataset is in GFW. If so, I'll move mnist dataset into the example image.

**Comment by DjangoPeng** [comment]
No changes. Just rebase.

**Comment by gaocegege-caicloud** [comment]
Does the mnist-data is placed in the image? If it does we could merge the PR :thinking:

**Comment by DjangoPeng** [comment]
Of course, and I think you have tested if before. 

See also: https://github.com/caicloud/dockerfile/pull/16

**Pull request merged**
